# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: pranish.belsare24@vit.edu
author_name: ThePranish03
cloud_provider: vercel
contract_name: clubledger
deployment_language: python
preset_name: production
project_name: clubledger

